name: deploy to vercel

on:
  push:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: /github/workspace
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build Vercel dist via Docker
        uses: ./.github/actions/docker

      - name: Deploying to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
