name: deploy to vercel

on:
  push:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t portoimage:latest -f .github/actions/docker/Dockerfile .

      - name: Run Docker container
        run: docker run --name portocontainer -p 3000:3000 -d portoimage:latest

      - name: Deploying to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
